apiVersion: bucket/v1
kind: Schema
metadata:
  name: customer
spec:
  title: ASSET-Customer
  description: ASSET-Customer description
  required:
    - email
  acl:
    write: "true==true"
    read: "true=true"
  properties:
    name:
      type: string
    email:
      type: string
    stripe_customer_id:
      type: string
    status:
      type: string
      default: creating
      enum:
        - creating
        - done
        - error
