# CUSTOMER BUCKET
apiVersion: bucket/v1
kind: Schema
metadata:
  name: customer
spec:
  title: ASSET-Customer
  description: ASSET-Customer description
  required:
    - email
  acl:
    write: "true==true"
    read: "true=true"
  properties:
    name:
      type: string
    email:
      type: string
    stripe_customer_id:
      type: string
    status:
      type: string
      default: creating
      enum:
        - creating
        - done
        - error
---
# PAYMENT METHOD BUCKET
apiVersion: bucket/v1
kind: Schema
metadata:
  name: payment-method
spec:
  title: ASSET-Payment Method
  description: ASSET-Payment Method description
  required:
    - payment_method_id
  acl:
    write: "true==true"
    read: "true=true"
  properties:
    customer:
      type: relation
      relationType: onetoone
      bucket:
        resourceFieldRef:
          bucketName: customer
    payment_method_id:
      type: string
    status:
      type: string
      default: creating
      enum:
        - creating
        - done
        - error
    default:
      type: boolean
      default: false
---
# PRODUCT BUCKET
apiVersion: bucket/v1
kind: Schema
metadata:
  name: product
spec:
  title: ASSET-Product
  description: ASSET-Product description
  required:
    - name
  acl:
    write: "true==true"
    read: "true=true"
  properties:
    name:
      type: string
    status:
      type: string
      default: creating
      enum:
        - creating
        - done
        - error
    product_id:
      type: string
---
# PLAN BUCKET
apiVersion: bucket/v1
kind: Schema
metadata:
  name: plan
spec:
  title: ASSET-Plan
  description: ASSET-Plan description
  required:
    - currency
    - interval
    - product
    - amount
  acl:
    write: "true==true"
    read: "true=true"
  properties:
    product:
      type: relation
      bucket:
        resourceFieldRef:
          bucketName: product
    interval:
      type: string
      default: month
      enum:
        - day
        - week
        - month
        - year
  amount:
    type: number
  currency:
    type: string
    default: usd
  status:
    type: string
    default: creating
    enum:
      - creating
      - done
      - error
  price_id:
    type: string
    description: Filled AUTOMATICALLY
---
# PAYMENT BUCKET
apiVersion: bucket/v1
kind: Schema
metadata:
  name: payment
spec:
  title: ASSET-Payment
  description: ASSET-Payment description
  required:
    - payment_type
  acl:
    write: "true==true"
    read: "true=true"
  properties:
    customer:
      type: relation
      bucket:
        resourceFieldRef:
          bucketName: customer
    payment_method:
      type: relation
      bucket:
        resourceFieldRef:
          bucketName: payment-method
    payment_type:
      type: string
      enum:
        - subscribe
        - invoice
        - charge
    token:
      type: string
    price:
      type: number
    currency:
      type: string
      default: usd
    status:
      type: string
      default: creating
      enum:
        - creating
        - done
        - error
    plan:
      type: relation
      bucket:
        resourceFieldRef:
          bucketName: plan
---
# API KEY
apiVersion: passport/v1
kind: ApiKey
metadata:
  name: access-to-buckets-apikey
spec:
  name: Secret Api Key For Stripe Asset
  policies:
    - BucketFullAccess
---
# FUNCTION
apiVersion: function/v1
kind: Function
metadata:
  name: stripe-function
spec:
  title: Stripe Functions
  description: Stripe Functions description
  timeout: 50
  code: ./function/triggers.js
  runtime:
    name: Node
    language: Javascript
  environment:
    - name: SECRET_API_KEY
      valueFrom:
        resourceFieldRef:
          apiKeyName: access-to-buckets-apikey
    - name: STRIPE_TEST
      value: "stripe secret test here"
    - name: CUSTOMER_BUCKET_ID
      valueFrom:
        resourceFieldRef:
          schemaName: customer
    - name: PAYMENT_METHOD_ID
      valueFrom:
        resourceFieldRef:
          schemaName: payment-method
    - name: PRODUCT_BUCKET_ID
      valueFrom:
        resourceFieldRef:
          schemaName: product
    - name: PLAN_BUCKET_ID
      valueFrom:
        resourceFieldRef:
          schemaName: plan
    - name: PAYMENT_BUCKET_ID
      valueFrom:
        resourceFieldRef:
          schemaName: payment
  dependency:
    - name: "@spica-devkit/bucket"
      version: latest
    - name: "node-fetch"
      version: latest
    - name: stripe
      version: latest
---
# CUSTOMER TRIGGER
apiVersion: function/v1
kind: Trigger
metadata:
  name: customer-trigger
spec:
  name: customer
  func: stripe-function
  type: bucket
  bucketOptions:
    bucket:
      resourceFieldRef:
        schemaName: customer
    phase: AFTER
    type: INSERT
---
# PAYMENT METHOD TRIGGER
apiVersion: function/v1
kind: Trigger
metadata:
  name: payment-method-trigger
spec:
  name: paymentMethod
  func: stripe-function
  type: bucket
  bucketOptions:
    bucket:
      resourceFieldRef:
        schemaName: payment-method
    phase: AFTER
    type: INSERT
---
# PAYMENT TRIGGER
apiVersion: function/v1
kind: Trigger
metadata:
  name: payment-trigger
spec:
  name: payment
  func: stripe-function
  type: bucket
  bucketOptions:
    bucket:
      resourceFieldRef:
        schemaName: payment
    phase: AFTER
    type: INSERT
---
# PRODUCT TRIGGER
apiVersion: function/v1
kind: Trigger
metadata:
  name: product-trigger
spec:
  name: product
  func: stripe-function
  type: bucket
  bucketOptions:
    bucket:
      resourceFieldRef:
        schemaName: product
    phase: AFTER
    type: INSERT
---
# PLAN TRIGGER
apiVersion: function/v1
kind: Trigger
metadata:
  name: plan-trigger
spec:
  name: plan
  func: stripe-function
  type: bucket
  bucketOptions:
    bucket:
      resourceFieldRef:
        schemaName: plan
    phase: AFTER
    type: INSERT
